---
- name: My first play
  hosts: propenta
  gather_facts: false
  become: true
  pre_tasks:
    - name: Fix broken dependencies
      ansible.builtin.shell: apt --fix-broken install -y
      become: yes
    - name: Update all packages
      apt:
        name: '*'
        state: latest

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600




  tasks:
   - name: Print message
     ansible.builtin.debug:
      msg: ROBERTO CONFIGS
  roles:
    - roles/nginx
    # - roles/remove_nginx
    # - roles/postgreSQL
    # - roles/MongoDB
    # - roles/ceph
    # - roles/nodejs
    # - roles/openvpn




