---
# tasks file for network
- name: netplan installation
  ansible.builtin.apt:
    name:
      - netplan.io
    state: present

- name:  started task
  ansible.builtin.systemd:
    name: netplan.service
    enabled: true
    state: started
  notify: restart-task


- name: Configurer l'interface réseau
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify:
    - Redémarrer les services réseau
